### PR TITLE
Add support for Xcode's 'Shared Folder' and 'Custom' Derived Data location setting

### PR DESCRIPTION
**Pull request by RuudPuts**
Like me, many developers use the 'Shared Folder' or 'Custom' location for their build and products, which can be set in Xcode's preferences via the 'Locations' tab and than clicking the 'Advanced...' button next to Derived Data.

When building your Calabash target for profiling, to use with start_test_server_in_background this would result in Calabash not being able to find your .app file. The pull request is an addition in simulator_launcher.rb which adds support for Xcode's Derived Data location setting when searching for the .app file to launch.

### CODE REVIEW

**Comment by jmoody** [comment]
@RuudPuts Thanks for the pull-request.

Finding the .app is a challenging problem and one that we have wrestled with since day one.

I have a couple of concerns beyond the code comments.

* Is this backward compatible to Xcode 5?  One reason that we don't do more on this problem is that we don't want to chase Xcode more than we already do.
* Does this have any effect on Xamarin Studio users?  I know you cannot test this, but someone will have to investigate.
* There are no tests that demonstrate this working.

**Comment by RuudPuts** [comment]
Thanks for your reply Joshua. I'll implement PlistBuddy, add the tests and test on Xcode 5 and get back to this.

**Comment by jmoody** [comment]
@RuudPuts This is an _excellent_ PR and really good idea.

I am going to implement this in run-loop so it can be leveraged for Calabash 2.0.

There are a couple edge cases that need to be sorted out.  Shall I @mention you in the run-loop PR so you can track progress?

Nice work!

+100

**Comment by RuudPuts** [comment]
@jmoody That would be awesome! Really looking forward to it, thanks!

**Comment by jmoody** [comment]
After investigating this issue some more, I see this is a non-trivial problem.  Implementing this code in run-loop will take a significant amount of time - I have started by there are many cases to handle.

I have decided I am going to merge this PR as is.  It probably won't break anything and it looks to me like it work for most cases.

Thanks!

**[iOS] Automatically detect application in xcode project** [#23](https://github.com/calabash/calabash/issues/23)

**Comment by arulami** [comment]
"start_test_server_in_background"  and it throws error "no implicit conversion of nil in to String" for Calabash 0.17.0

Error:

TypeError: no implicit conversion of nil into String
	from /Users/xxxx8/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/launch/simulator_launcher.rb:255:in `join'
	from /Users/xxxx8/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/launch/simulator_launcher.rb:255:in `app_bundle_or_raise'
	from /Users/xxxx8/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/launcher.rb:541:in `relaunch'
	from /Users/xxxxx/.rvm/gems/ruby-2.1.5/gems/calabash-cucumber-0.17.0/lib/calabash-cucumber/core.rb:943:in `start_test_server_in_background'
	from (irb):1
	from /Users/a042468/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'

cucumber command is working fine for 0.17.4 and it also  requires APP_BUNDLE_PATH to set up in 01_launch.rb file explicitly to find an app path and it could not find .app path by itself.

If I specify APP Variable 'APP_BUNDLE_PATH' its able to find app.

But it could not find an app path while running in DEBUG mode i.e calabash-ios console, start_test_server_in_background even if i specified in APP variable

Thanks
Arul

**Comment by jmoody** [comment]
@arulami It would have been better if you created a new issue.  A comment on a closed pull request will get lost.

Tracking this problem here:

* 0.17.0 Cannot automatically detect app #959

**Pull request merged**
