### PR TITLE
Added Calabash.podspec

### PR DESCRIPTION
**Pull request by ark-konopacki**
Calabash pod downloaded about 59 000 times, and it not official way of release distribution.
I want to add an example podspec  file to repo if anyone wants to use newest calabash as a pod.

### CODE REVIEW

**Comment by jmoody** [comment]
I appreciate the effort.  I am not sure I can merge this.  I have mixed feelings about people using CocoaPods to integrate Calabash into their apps. 

Please see [How to Add Calabash to Xcode: CocoaPods](https://github.com/calabash/calabash-ios/wiki/Tutorial%3A-How-to-add-Calabash-to-Xcode#cocoapods) for a complete discussion.

In any event, before merging I would want to see an app + tests to show how to using the file.

**Comment by ark-konopacki** [comment]
@jmoody: Maybe I should add some readme section like how to add calabash using local podspec file? Or create a folder like Pods or something. BWT I write to @krukow  and if I will have possibility to upload updated spec to CocoaPods then we can close that PR.

**Comment by jmoody** [comment]
> README

I am trying to reduce the size of the README.md to make it easier to get started so I don't want any more content there.

> I will have possibility to upload updated spec to CocoaPods then we can close that PR.

We don't own the CocoaPods spec.  I think you can just submit an update.  I think Karl would appreciate it. 

Thanks!

**Comment by ark-konopacki** [comment]
@jmoody:
> We don't own the CocoaPods spec. I think you can just submit an update. I think Karl would appreciate it.
Since Karl uploaded first spec to CocoaPods he is registered as a owner :) and i try to upload it with no success. 
@krukow i checked and you should only give me permission like:
`$ pod trunk add-owner Calabash email@example.com` email should be mine, 
and after that i can upload updated specs to Cocoapods

**Comment by choefele** [comment]
I'd appreciate if you supported CocoaPods – it's the de-facto standard for integrating iOS libraries and makes developer's life a lot easier.

**Comment by krukow** [comment]
We will support it.

On Fri, 8 Jan 2016 at 22:35, Claus Höfele <notifications@github.com> wrote:

> I'd appreciate if you supported CocoaPods – it's the de-facto standard for
> integrating iOS libraries and makes developer's life a lot easier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calabash/calabash-ios/pull/979#issuecomment-170134548>
> .
>
-- 
Karl Krukow, Xamarin Test Cloud
Phone: +45 26 84 90 79
Xamarin 4: everything you need to Build, Test, Monitor, and Accelerate
amazing mobile apps. xmn.io/xamarin4

**Comment by greenhippie** [comment]
+1 for CocoaPods support! -- ([calabash-ios-with-cocoapods-and-build-configurations](http://www.mokacoding.com/blog/calabash-ios-with-cocoapods-and-build-configurations/))
I very much prefer the pod + -cal scheme approach to checking in the calabash.framework or automating calling the calabash-ios setup command (only because I have had reliability issues using the calabash-ios setup command ... and it isn't documented to work for XCode7)

**Comment by jmoody** [comment]
Jenkins test this please.

**Comment by jmoody** [comment]
Jenkins test this please.

**Comment by ark-konopacki** [comment]
@jmoody podspec updated, should I add some example or adding calabash pod manual?

**Comment by jmoody** [comment]
@ark-konopacki Thanks for the update.  I am waiting for @sapieneptus to come on line to discuss whether we should use an S3 URL.

> example

No.  This is no longer necessary.

Thanks!

**Comment by anthonye2007** [comment]
CocoaPods support would be great!

**Comment by greenhippie** [comment]
I am not sure if anyone has tried putting something like this in their project Podfile:
pod 'Calabash', :git => 'https://github.com/ark-konopacki/calabash-ios.git', :branch => 'feature/calabash-pod-specs', :configurations => ['Calabash']
... but the prepare_command does not appear to work (I get the following error):
Pre-downloading: `Calabash` from `https://github.com/ark-konopacki/calabash-ios.git`, branch `feature/calabash-pod-specs` [!] /bin/bash -c set -e tar xzf data.tar.gz unzip staticlib/calabash.framework.zip tar: Error opening archive: Failed to open 'data.tar.gz'

**Comment by ark-konopacki** [comment]
@greenhippie it shouldn't work in that way
can you try download Calabash.podspec to your project folder and update Podfile like:
`pod 'Calabash', :podspec => 'Calabash.podspec'`?

**Comment by jmoody** [comment]
@greenhippie The problem is that the calabash.framework.zip does not exist in the git repo - it only exists in the released gem.

**Comment by jmoody** [comment]
Tested locally and pushed.

* https://github.com/calabash/ios-setup-examples/tree/demo/cocoapods-config
* https://github.com/CocoaPods/Specs/tree/master/Specs/Calabash/0.17.1

**Pull request merged**
