### PR TITLE
Podspec path to server should be "Calabash" not "calabash"

### PR DESCRIPTION
**Pull request by ark-konopacki**
Resolves **Podspec typo?** #1097

### CODE REVIEW

**Comment by jmoody** [comment]
I do not want to merge this because I don't know why the lowercase vs uppercase `C` is causing a problem.  

I also want to see an integration tests: stand up a project in this repo that uses the podspec and getting running in CI.  Without such a test, I don't want to make any changes.

**Comment by ark-konopacki** [comment]
@jmoody i'm afraid what i was changed to small letter by mistake with other fixes see:https://github.com/calabash/calabash-ios/commit/7f6bad1bdeb78519caa5dad58bd359bf0161f792. And sure we should have a tests for that. At least someone should check it with clear env.

**Comment by jmoody** [comment]
I see the problem.

I still want an integration project in this repo that we can run locally and in CI.

**Comment by jmoody** [comment]
Upon reflection, I do _not_ want an end-to-end Cocoapods test in this repo.

1. This project should not have an dependencies on CocoaPods; users should be able to run the tests without installing CocoaPods.
2. The podspec should not be in this repository, it should be in the calabash-ios-server repository.  At the moment the spec relies on the fact that framework is shipped with the gem.  That will not always be the case.

Merging as is.

**Pull request merged**
