### PR TITLE
Added resizing for screenshot method

### PR DESCRIPTION
**Pull request by ark-konopacki**
using https://github.com/sdsykes/fastimage_resize
libgd should be installed (brew for example)
related to https://github.com/calabash/calabash-ios/issues/1043

### CODE REVIEW

**Comment by ark-konopacki** [comment]
@jmoody can you check that happens with Travis?

**Comment by jmoody** [comment]
Travis has been down for macOS since last night.

**Comment by ark-konopacki** [comment]
@jmoody I update implementation now it only works if we have gem `fastimage_resize` installed and shouldn't fail with `LoadError` if gem missing.

**Comment by ark-konopacki** [comment]
@jmody since this functionality now available as https://rubygems.org/gems/cal-screenshot-resize
i think this PR and https://github.com/calabash/calabash-ios/issues/1043 can be closed 
ATTN @TeresaP

**Comment by jmoody** [comment]
Thanks @ark-konopacki !!!

**Pull request closed without merging**
