### PR TITLE
Map: rename map to fetch_results

### PR DESCRIPTION
**Pull request by svandeven**
Map is conflicting with other tools - like mockserver-client.

My tests failed due to this error

```
 wrong number of arguments (0 for 2+) (ArgumentError)
      /Users/svandeven/dev/mobile/calabash-ios/calabash-cucumber/lib/calabash-cucumber/map.rb:52:in `map'
      /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/logging-1.8.2/lib/logging/color_scheme.rb:173:in `[]='
      /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/logging-1.8.2/lib/logging/color_scheme.rb:141:in `block in load_from_hash'
```

### CODE REVIEW

**Comment by jmoody** [comment]
Jenkins test this please

**Comment by jmoody** [comment]
@TobiasRoikjer @krukow @sapieneptus 

I paired with @svandeven this morning to solve this problem.  We have to be more defensive about overriding Kernel methods and methods that are defined as part of the ruby API.

Ultimately, I think the problem is the interaction with Calabash, Cucumber, and logging gem.

I am in favor of merging this as part of the 0.19.0 release.

**Comment by TobiasRoikjer** [comment]
@jmoody I am all for renaming map

**Comment by jmoody** [comment]
Hey @svandeven.  I am going to close this PR.  We need a slightly different solution which I will create.

Expect a fix in the next pre-release.

Thank you for your patience.

**Pull request closed without merging**
