### PR TITLE
Add ruby API for resetting the simulator content and settings

### PR DESCRIPTION
**Pull request by ark-konopacki**
I hope it is final version :)
https://github.com/calabash/calabash-ios/issues/924

### CODE REVIEW

**Comment by jmoody** [comment]
Looks good.  This will have to wait unit 0.17.1.

Any chance you want to try to write some rspec tests for this?

**Comment by jmoody** [comment]
Jenkins test this please

**Comment by jmoody** [comment]
@ark-konopacki I added unit and integration rspec tests and refactored your method.

Let me know if you approve.

**Comment by ark-konopacki** [comment]
@jmoody you have my approve

**Pull request closed without merging**
